import { TutorialSection } from './types';

export const TUTORIAL_SECTIONS: TutorialSection[] = [
  {
    id: 'onboarding',
    title: 'Quick onboarding',
    description: 'A short guided tour to help you understand how Pivoo supports your growth workflow.',
    steps: [
      {
        id: 'onboarding-dashboard',
        route: '/dashboard',
        target: '[data-tutorial-id="nav-dashboard"]',
        title: 'Start from Dashboard',
        description: 'This is your daily command center. Check progress, priorities, and consistency in one glance.',
      },
      {
        id: 'onboarding-goals',
        route: '/goals',
        target: '[data-tutorial-id="goals-add"]',
        title: 'Create meaningful goals',
        description: 'Build outcome and process goals here. Start with one focused goal to keep momentum high.',
      },
      {
        id: 'onboarding-goals-task-view',
        route: '/goals',
        target: '[data-tutorial-id="goals-view-toggle"]',
        title: 'Switch your perspective',
        description: 'Toggle between high-level planning and execution tasks so you can plan and act faster.',
      },
      {
        id: 'onboarding-self-discovery',
        route: '/self-discovery',
        target: '[data-tutorial-id="self-discovery-tabs"]',
        title: 'Align your direction',
        description: 'Use Self Discovery to clarify values, vision, and focus areas before deep execution.',
      },
      {
        id: 'onboarding-journal',
        route: '/journaling',
        target: '[data-tutorial-id="nav-journaling"]',
        title: 'Capture your journal rhythm',
        description: 'Use Journaling to register weekly and monthly sentiment, then review trends in one monthly summary.',
      },
      {
        id: 'onboarding-ai',
        route: '/ai-chatbot',
        target: '[data-tutorial-id="ai-modules-grid"]',
        title: 'Use AI for investigation',
        description: 'Pick an AI module to analyze your goals and context, then refine with follow-up chat.',
      },
      {
        id: 'onboarding-tutorial-menu',
        target: '[data-tutorial-id="drawer-tutorial"]',
        title: 'Replay any section later',
        description: 'Open Tutorial from the sidebar anytime to revisit specific sections at your own pace.',
      },
    ],
  },
  {
    id: 'dashboard-overview',
    title: 'Dashboard Overview',
    description: 'Understand the high-value cards on your dashboard in under 2 minutes.',
    steps: [
      {
        id: 'dash-main',
        route: '/dashboard',
        target: '[data-tutorial-id="dashboard-year-progress"]',
        title: 'Year progress at a glance',
        description: 'This card summarizes your yearly momentum and key indicators so you can decide your next action quickly.',
      },
      {
        id: 'dash-focus',
        route: '/dashboard',
        target: '[data-tutorial-id="dashboard-today-focus"]',
        title: 'Today focus',
        description: 'Use this block to execute what matters now. Keep daily work aligned with bigger goals.',
      },
      {
        id: 'dash-reflection',
        route: '/dashboard',
        target: '[data-tutorial-id="dashboard-reflection"]',
        title: 'Close the loop with reflection',
        description: 'Reflection helps you learn from execution and improve consistency week after week.',
      },
      {
        id: 'dash-advanced-tutorials',
        target: '[data-tutorial-id="drawer-tutorial"]',
        title: 'Find advanced tutorials',
        description: 'Open Tutorial in the side menu to access advanced walkthroughs for each area of the app.',
      },
    ],
  },
  {
    id: 'goals-management',
    title: 'Goals Management',
    description: 'Navigate your goals workspace and key controls quickly.',
    steps: [
      {
        id: 'gm-header',
        route: '/goals',
        target: '[data-tutorial-id="goals-header"]',
        title: 'Goals workspace',
        description: 'This area is where planning and tracking happen. Keep your goals clear, measurable, and active.',
      },
      {
        id: 'gm-status',
        route: '/goals',
        target: '[data-tutorial-id="goals-status-tabs"]',
        title: 'Status filters',
        description: 'Use tabs to focus on active, completed, or archived goals without clutter.',
      },
      {
        id: 'gm-content',
        route: '/goals',
        target: '[data-tutorial-id="goals-content"]',
        title: 'Execution area',
        description: 'Your goal cards and task blocks appear here. Review this area often to stay on track.',
      },
    ],
  },
  {
    id: 'task-view',
    title: 'Task view',
    description: 'Learn how to move from planning to concrete action.',
    steps: [
      {
        id: 'tv-toggle',
        route: '/goals',
        target: '[data-tutorial-id="goals-view-toggle"]',
        title: 'Switch to Task view',
        description: 'Use this toggle to focus on actionable tasks across your goals.',
      },
      {
        id: 'tv-content',
        route: '/goals',
        target: '[data-tutorial-id="goals-content"]',
        title: 'Work from tasks',
        description: 'Task view helps you execute daily actions and keep momentum visible.',
      },
      {
        id: 'tv-nav-back',
        target: '[data-tutorial-id="nav-goals"]',
        title: 'Return anytime',
        description: 'You can always reopen Goals from bottom navigation when it is time to execute.',
      },
    ],
  },
  {
    id: 'high-level-view',
    title: 'High-level view',
    description: 'Use strategic planning mode to prioritize your bigger outcomes.',
    steps: [
      {
        id: 'hl-toggle',
        route: '/goals',
        target: '[data-tutorial-id="goals-view-toggle"]',
        title: 'Switch to High-level view',
        description: 'This mode keeps strategy visible before diving into granular actions.',
      },
      {
        id: 'hl-status',
        route: '/goals',
        target: '[data-tutorial-id="goals-status-tabs"]',
        title: 'Prioritize with status tabs',
        description: 'Filter by lifecycle stage to review where your strategic attention is needed most.',
      },
      {
        id: 'hl-cards',
        route: '/goals',
        target: '[data-tutorial-id="goals-content"]',
        title: 'Review goal cards',
        description: 'Goal cards summarize progress and help you decide what to adjust next.',
      },
    ],
  },
  {
    id: 'goal-creation',
    title: 'Goal creation',
    description: 'Create your first meaningful goal in a few guided steps.',
    steps: [
      {
        id: 'gc-entry',
        route: '/goals',
        target: '[data-tutorial-id="goals-add"]',
        title: 'Add a new goal',
        description: 'Tap this button to open the goal creation dialog and start your planning flow.',
      },
      {
        id: 'gc-types',
        route: '/goals',
        target: '[data-tutorial-id="goals-view-toggle"]',
        title: 'Prepare execution context',
        description: 'After creating a goal, switch views to verify both strategy and daily execution.',
      },
      {
        id: 'gc-review',
        route: '/goals',
        target: '[data-tutorial-id="goals-content"]',
        title: 'Track your new goal',
        description: 'Your goal appears here so you can monitor progress and iterate over time.',
      },
    ],
  },
  {
    id: 'self-discovery',
    title: 'Self Discovery',
    description: 'Clarify personal direction before optimizing performance.',
    steps: [
      {
        id: 'sd-tabs',
        route: '/self-discovery',
        target: '[data-tutorial-id="self-discovery-tabs"]',
        title: 'Work section by section',
        description: 'Move through Life Wheel, Values, Vision, and Year Focus in short blocks.',
      },
      {
        id: 'sd-wheel',
        route: '/self-discovery',
        target: '[data-tutorial-id="self-discovery-wheel-toggle"]',
        title: 'Assess your current reality',
        description: 'Use chart or list mode to reflect on where you are and where to improve.',
      },
      {
        id: 'sd-summary',
        route: '/self-discovery',
        target: '[data-tutorial-id="self-discovery-summary"]',
        title: 'Use summary for quick review',
        description: 'Open summary to check your full self-discovery snapshot without re-reading everything.',
      },
    ],
  },

  {
    id: 'journaling',
    title: 'Journaling',
    description: 'Track weekly and monthly sentiment while keeping your reflection history visible in one place.',
    steps: [
      {
        id: 'jr-nav',
        route: '/journaling',
        target: '[data-tutorial-id="nav-journaling"]',
        title: 'Open the journal area',
        description: 'Access Journaling from bottom navigation to evaluate your week and reflect on each month.',
      },
      {
        id: 'jr-tabs',
        route: '/journaling',
        target: '[data-tutorial-id="journaling-tabs"]',
        title: 'Switch between entry and summary',
        description: 'Use the tabs to fill current entries and review month-by-month progression in the yearly summary.',
      },
      {
        id: 'jr-monthly',
        route: '/journaling',
        target: '[data-tutorial-id="journaling-monthly-reflection"]',
        title: 'Complete monthly reflection',
        description: 'Rate overall monthly sentiment, answer the three evaluation questions, and capture your open reflection text.',
      },
    ],
  },
  {
    id: 'ai-assistant',
    title: 'AI Assistant',
    description: 'Use Pivoo AI to generate focused analysis and decisions.',
    steps: [
      {
        id: 'ai-grid',
        route: '/ai-chatbot',
        target: '[data-tutorial-id="ai-modules-grid"]',
        title: 'Choose the right module',
        description: 'Each module is specialized. Pick one based on your current decision or challenge.',
      },
      {
        id: 'ai-side',
        route: '/ai-chatbot',
        target: '[data-tutorial-id="ai-module-sidebar"]',
        title: 'Set your context',
        description: 'Provide clear context to improve AI output quality and relevance.',
      },
      {
        id: 'ai-output',
        route: '/ai-chatbot',
        target: '[data-tutorial-id="ai-analysis-output"]',
        title: 'Act on recommendations',
        description: 'Use the generated analysis to decide what to do next in goals and execution.',
      },
    ],
  },
  {
    id: 'chat',
    title: 'Chat',
    description: 'Use follow-up conversation to deepen understanding and next actions.',
    steps: [
      {
        id: 'chat-entry',
        route: '/ai-chatbot',
        target: '[data-tutorial-id="ai-chat-interface"]',
        title: 'Continue with chat',
        description: 'After analysis starts, use chat for follow-up questions and practical implementation advice.',
      },
      {
        id: 'chat-context',
        route: '/ai-chatbot',
        target: '[data-tutorial-id="ai-module-sidebar"]',
        title: 'Keep context aligned',
        description: 'Adjust module inputs when needed so chat remains grounded in your actual goals.',
      },
      {
        id: 'chat-iterate',
        route: '/ai-chatbot',
        target: '[data-tutorial-id="ai-analysis-output"]',
        title: 'Iterate fast',
        description: 'Review analysis, ask for refinements, then convert insights into concrete actions.',
      },
    ],
  },
  {
    id: 'functions',
    title: 'Functions',
    description: 'Understand the functional blocks available in the AI workspace.',
    steps: [
      {
        id: 'fn-modules',
        route: '/ai-chatbot',
        target: '[data-tutorial-id="ai-modules-grid"]',
        title: 'Functions are module-based',
        description: 'Each module is a function with a specific analytical purpose and output style.',
      },
      {
        id: 'fn-config',
        route: '/ai-chatbot',
        target: '[data-tutorial-id="ai-analysis-configurator"]',
        title: 'Configure before launching',
        description: 'Set inputs and constraints to receive focused and actionable outputs.',
      },
      {
        id: 'fn-chat',
        route: '/ai-chatbot',
        target: '[data-tutorial-id="ai-chat-interface"]',
        title: 'Compose workflows with chat',
        description: 'Use chat as an extension of module functions to explore alternatives quickly.',
      },
    ],
  },
  {
    id: 'investigations',
    title: 'Investigations',
    description: 'Run structured investigations to uncover blockers and opportunities.',
    steps: [
      {
        id: 'inv-start',
        route: '/ai-chatbot',
        target: '[data-tutorial-id="ai-modules-grid"]',
        title: 'Start an investigation',
        description: 'Select an investigation-focused module based on your current objective.',
      },
      {
        id: 'inv-results',
        route: '/ai-chatbot',
        target: '[data-tutorial-id="ai-analysis-output"]',
        title: 'Inspect generated insights',
        description: 'Read patterns, root causes, and recommendations to make sharper decisions.',
      },
      {
        id: 'inv-refine',
        route: '/ai-chatbot',
        target: '[data-tutorial-id="ai-chat-interface"]',
        title: 'Refine with follow-up',
        description: 'Ask clarifying questions until the output is concrete enough to execute.',
      },
    ],
  },
];
